### ISSUE TITLE
After the login of the new user shows the` log-out button` instead of` log-in/SignUp` button.

### ISSUE THREAD

**Issue by deep1296** [bhav1kmaru/apnaMall#22]
<img width="838" alt="Screenshot 2023-03-01 171454" src="https://user-images.githubusercontent.com/96063026/222130482-2539af24-e0b8-4064-bbb8-c1ebfe6e55cc.png">

**Comment by bhav1kmaru** [comment]
User can now see the sign out button after login.
![image](https://user-images.githubusercontent.com/60300103/222660498-8095753c-f7de-4d3e-b106-b5a4809541a7.png)

**Comment by deep1296** [comment]
Done
