### ISSUE TITLE
Fix the design issue `Sorting dropdown is coming outside the div` and increase the div size

### ISSUE THREAD

**Issue by deep1296** [bhav1kmaru/apnaMall#25]
<img width="134" alt="Screenshot 2023-03-01 171907" src="https://user-images.githubusercontent.com/96063026/222131585-2a237380-f30d-4db2-a8c8-68d7a03dfecf.png">

**Comment by bhav1kmaru** [comment]
Fixed the design issue in sorting.
![image](https://user-images.githubusercontent.com/60300103/222659954-bd6d275a-ee02-4e3c-92ce-3337b7e76d67.png)
