### ISSUE TITLE
Add validations to following

### ISSUE THREAD

**Issue by deep1296** [bhav1kmaru/apnaMall#28]
- [ ] Card number should be 16 digits only.
- [ ] CVV should be 3 digits only.
- [ ] Name should not be empty

**Comment by deep1296** [comment]
<img width="319" alt="Screenshot 2023-03-01 172809" src="https://user-images.githubusercontent.com/96063026/222133510-3502cac2-f5a2-49aa-b85b-780359f327d3.png">

**Comment by bhav1kmaru** [comment]
The Pay button will now be disabled unless all fields are filled and validated. Card Number should be 16 digits only, CVV should be 3 digits only. Name should not be empty.
![image](https://user-images.githubusercontent.com/60300103/222659223-feff2d72-a690-462b-9d32-e7d93c1b3b78.png)
![image](https://user-images.githubusercontent.com/60300103/222659419-bffef852-ff20-4e10-8361-7e87fc436e30.png)
