### ISSUE TITLE
Show the `product information` in checkout page like price and all.

### ISSUE THREAD

**Issue by deep1296** [bhav1kmaru/apnaMall#29]

**Comment by bhav1kmaru** [comment]
Product Information is now visible on cart page and checkout page

![image](https://user-images.githubusercontent.com/60300103/222658742-965c472e-f643-4bee-9696-0151258e61ac.png)
![image](https://user-images.githubusercontent.com/60300103/222658958-2b30f33c-b473-4274-8270-10ba94fc7717.png)
