### ISSUE TITLE
Work on responsiveness 

### ISSUE THREAD

**Issue by deep1296** [bhav1kmaru/apnaMall#31]
- [x] Cart page is not responsive
<img width="218" alt="image" src="https://user-images.githubusercontent.com/96063026/222134726-d9238e48-4a08-404e-b248-386bee61e088.png">

**Comment by bhav1kmaru** [comment]
worked on it, the cart page is now responsive.
![image](https://user-images.githubusercontent.com/60300103/222658240-e986340d-64af-47b5-a1d4-95993c6edd76.png)
